version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: back-end-e-tax:latest
    ports:
      - "2801:8080"
    environment:
      - PORT=8080
    restart: unless-stopped
