server:
  port: ":8080"

database:
  host: "43.229.76.109"
  port: 5432
  user: "postgres"
  password: "a26c375687"
  dbname: "admin_tax"
  sslmode: "disable"

auth:
  # The JWT secret can either be the secret value itself or a path to a file
  # containing the secret. When a file path is provided it will be read during
  # application startup.
  jwt_secret: "./configs/jwt/private.pem"
  jwt_expiry_access_minutes: 15
  jwt_expiry_refresh_hours: 24
