server:
  port: ":8080"

database:
  host: "YOUR_DB_HOST"
  port: 5432
  user: "YOUR_DB_USER"
  password: "YOUR_DB_PASSWORD"
  dbname: "YOUR_DB_NAME"
  sslmode: "disable"

auth:
  # JWT secret should be provided via the JWT_SECRET environment variable
  jwt_secret: ""
  jwt_issuer: "invoice_service"
  jwt_audience: "invoice_api"
  jwt_expiry_access_minutes: 15
  jwt_expiry_refresh_hours: 24
